### ISSUE TITLE
Question: Would CO-RE-enabled `PT_REGS_xxx_CORE` solves the same issue? 

### ISSUE THREAD

**Issue by ShawnZhong** [eunomia-bpf/multiarch-relocate-example#1]
Hi, I couldn't find a place for discussion, so I opened this issue. 

It is nice that you can relocate `pt_regs` to work on different architectures! 

However, I am wondering how this approach compares to the CO-RE-enabled `PT_REGS_xxx_CORE` macros. 
From its commit message in https://github.com/libbpf/libbpf/commit/64bd9e074b6a348854794845beb22b90a4052fb2: 

```
This patch adds CO-RE variants of those macros that use BPF_CORE_READ() to
read necessary fields. This provides relocatable architecture-agnostic pt_regs
field accesses.
```

**Comment by Officeyutong** [comment]
Register names are still hard coded when using PT_REGS_xxx_CORE

**Comment by Officeyutong** [comment]
> Register names are still hard coded when using PT_REGS_xxx_CORE

Means that if you compile your eBPF program on x86, an CORE record to access pt_regs.di will be emitted, which is unable to relocate on non-x86 platforms

**Comment by ShawnZhong** [comment]
Thank you so much for the explanation! 

I used to think that the definition of `PT_REGS_PARMx_CORE` normalized the access to registers by casting everything to a common struct type so it works across architectures. 

```
#define PT_REGS_PARM1_CORE(x) BPF_CORE_READ(__PT_REGS_CAST(x), __PT_PARM1_REG)
```

After a closer look, you are right that register names are still hard-coded. On x86, we have 

```
#define __PT_REGS_CAST(x) (x)
#define __PT_PARM1_REG di
```

And `BPF_CORE_READ` would indeed generate a relocation record. (Maybe to deal with offset changes over kernel source code versions but not over architectures? I am not sure about the initial intent. )

Anyway, your repo is quite a useful way to utilize the relocation records for `pt_regs`. I hope to see it integrated into `libbpf` someday!

**Comment by ShawnZhong** [comment]
BTW, I have found some similar logic for translating register name to offset in `pt_regs` in `libbpf`, but for USDT: 

https://github.com/libbpf/libbpf/blob/02724cfd0702c4102138e62c3ae7d2721c7b190e/src/usdt.c#L1237-L1280
